"""empty message

Revision ID: 08813081adb7
Revises: 8b6007cd95a1
Create Date: 2025-05-01 04:46:13.874708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '08813081adb7'
down_revision = '8b6007cd95a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studySubjects', schema=None) as batch_op:
        batch_op.drop_column('opinion_toggle')
        batch_op.drop_column('graph_type')
        batch_op.drop_column('privacy')
        batch_op.drop_column('graph_scale')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('studySubjects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('graph_scale', sa.INTEGER(), nullable=False))
        batch_op.add_column(sa.Column('privacy', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('graph_type', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('opinion_toggle', sa.BOOLEAN(), nullable=False))

    # ### end Alembic commands ###
