"""Added LogSession Model

Revision ID: 36ec2d713155
Revises: 98c359384f33
Create Date: 2025-05-03 09:55:04.792945

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36ec2d713155'
down_revision = '98c359384f33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logsessions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=False),
    sa.Column('study_duration', sa.Integer(), nullable=True),
    sa.Column('break_time', sa.Integer(), nullable=True),
    sa.Column('mood_level', sa.Integer(), nullable=True),
    sa.Column('study_environment', sa.String(length=50), nullable=True),
    sa.Column('mental_load', sa.Integer(), nullable=True),
    sa.Column('distractions', sa.String(length=255), nullable=True),
    sa.Column('goal_progress', sa.String(length=20), nullable=True),
    sa.Column('focus_level', sa.Integer(), nullable=True),
    sa.Column('effectiveness', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('subject_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['subject_id'], ['subjects.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logsessions')
    # ### end Alembic commands ###
